// Generated by mvbar/scripts/sync-artwork-icons.mjs. Do not edit by hand.
// Source: mvbar/web/app/icons/artwork-icons.json (version 1).
package com.mvbar.android.ui.components

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

object ArtworkIcons {
    val Album: ImageVector by lazy {
        ImageVector.Builder("MVBaralbum", 24.dp, 24.dp, 24f, 24f)
            .addPath(
                pathData = PathParser().parsePathString("M6 3H18C19.657 3 21 4.343 21 6V18C21 19.657 19.657 21 18 21H6C4.343 21 3 19.657 3 18V6C3 4.343 4.343 3 6 3Z M17.5 12A5.5 5.5 0 1 1 6.5 12A5.5 5.5 0 1 1 17.5 12Z M13 12A1 1 0 1 1 11 12A1 1 0 1 1 13 12Z").toNodes(),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round
            ).build()
    }

    val Artist: ImageVector by lazy {
        ImageVector.Builder("MVBarartist", 24.dp, 24.dp, 24f, 24f)
            .addPath(
                pathData = PathParser().parsePathString("M16 7.5A4 4 0 1 1 8 7.5A4 4 0 1 1 16 7.5Z M4.5 20.5V18.5C4.5 15.739 7.858 13.5 12 13.5C16.142 13.5 19.5 15.739 19.5 18.5V20.5 M8 20.5H16").toNodes(),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 1.5f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round
            ).build()
    }
}
